GEF/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("", include('GEFs.urls')),
    path("admin/", admin.site.urls),
]

GEFs/urls.py
from django.urls import path
from . import views

app_name = 'GEFs'

urlpatterns = [
	#Pagina de inicio
	#path('usuario/<int:id_usuario>',views.usuario,name='usuario'),

	# path('filtro_cuenta/',views.filtro_cuenta,name='filtro_cuenta'),
	path('cuenta_registro/<int:id_cuenta>',views.cuenta_registro,name='cuenta_registro'),
	path('eliminar_registro/<int:id_registro>',views.eliminar_registro,name='eliminar_registro'),
	path('eliminar_cuenta/<int:id_cuenta>',views.eliminar_cuenta,name='eliminar_cuenta'),
	path('modificar_cuenta/<int:id_cuenta>',views.modificar_cuenta,name='modificar_cuenta'),
	path('nuevo_registro/',views.nuevo_registro,name='nuevo_registro'),
	path('nueva_cuenta/<int:id_usuario>',views.nueva_cuenta,name='nueva_cuenta'),
	path('cuentas/',views.cuentas,name='cuentas'),
	path('registros/',views.registros,name='registros'),
	path('login/',views.mi_login,name='login'),
	path('logout/',views.mi_logout,name='logout'),
	path('user_register/',views.user_register,name='user_register')
]

GEFs/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


# Create your models here.

class MiUsuarioManager(BaseUserManager):
    def create_user(self,username,password=None,**extra_fields):
        if not username:
            raise ValueError('El usuario debe tener username')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self_db)
        return user

    def create_superuser(self,username,password=None,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)

        return self.create_user(username,password,**extra_fields)

class Usuario(AbstractBaseUser, PermissionsMixin):
    id_usuario = models.AutoField(primary_key=True)
    username = models.CharField(unique=True, max_length=50)
    password= models.CharField(max_length=128)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=35)

    class Meta:
        db_table = 'usuario'

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = MiUsuarioManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        '''Devuelve una representacion del modelo como cadena'''
        return self.username

    def has_perm(self,perm,obj=None):
        return True

    def has_module_perms(self,app_label):
        return True

class Cuenta(models.Model):
    id_cuenta = models.AutoField(primary_key=True)
    nombre_cuenta = models.CharField(max_length=15)
    balance = models.FloatField()
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario', blank=True, null=True)

    class Meta:
        db_table = 'cuenta'

    def __str__(self):  
        '''Devuelve una representacion del modelo como cadena'''
        return self.nombre_cuenta

class Movimiento(models.Model):
    id_movimiento = models.AutoField(primary_key=True)
    tipo_movimiento = models.CharField(max_length=20)

    class Meta:
        db_table = 'movimiento'

    def __str__(self):
        '''Devuelve una representacion del modelo como cadena'''
        return self.tipo_movimiento

class Actividad(models.Model):
    id_actividad = models.AutoField(primary_key=True)
    tipo_actividad = models.CharField(max_length=50)
    id_movimiento = models.ForeignKey('Movimiento', models.DO_NOTHING, db_column='id_movimiento')

    class Meta:
        db_table = 'actividad'
        verbose_name_plural = 'Actividades'

    def __str__(self):
        '''Devuelve una representacion del modelo como cadena'''
        return self.tipo_actividad

class Subactividad(models.Model):
    id_subactividad = models.AutoField(primary_key=True)
    tipo_subactividad = models.CharField(max_length=50, blank=True, null=True)
    id_actividad = models.ForeignKey(Actividad, models.DO_NOTHING, db_column='id_actividad')

    class Meta:
        db_table = 'subactividad'
        verbose_name_plural ='Subactividades'

    def __str__(self):
        '''Devuelve una representacion del modelo como cadena'''
        return self.tipo_subactividad
        
class Formapago(models.Model):
    id_formapago = models.AutoField(db_column='id_formaPago', primary_key=True)  # Field name made lowercase.
    tipo_pago = models.CharField(max_length=20)

    class Meta:
        db_table = 'formapago'
        verbose_name_plural='Formas de pago'

    def __str__(self):
        '''Devuelve una representacion del modelo como cadena'''
        return self.tipo_pago

class Registros(models.Model):
    id_registro = models.AutoField(primary_key=True)
    importe = models.FloatField()
    fecha = models.DateField()
    hora = models.TimeField()
    beneficiario = models.CharField(max_length=50, blank=True, null=True)
    nota = models.TextField(blank=True, null=True)
    id_movimiento = models.ForeignKey(Movimiento, models.DO_NOTHING, db_column='id_movimiento', blank=True, null=True)
    id_actividad = models.ForeignKey(Actividad, models.DO_NOTHING, db_column='id_actividad', blank=True, null=True)
    id_subactividad = models.ForeignKey('Subactividad', models.DO_NOTHING, db_column='id_subactividad', blank=True, null=True)
    id_formapago = models.ForeignKey(Formapago, models.DO_NOTHING, db_column='id_formaPago', blank=True, null=True)  # Field name made lowercase.
    id_cuenta = models.ForeignKey(Cuenta, db_column='id_cuenta', on_delete=models.CASCADE, blank=True, null=True)
    id_usuario = models.ForeignKey('Usuario', db_column='id_usuario', on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'registros'
        verbose_name_plural ='Registros'

GEFs/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from .models import Usuario, Cuenta, Registros,Movimiento,Actividad,Subactividad
from .models import Formapago


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		if username and password:
			self.user = authenticate(username=username,password=password)
			if self.user is None:
				raise forms.ValidationError('Usuario o password incorrectos')
		return self.cleaned_data

	def get_user(self):
		return self.user

class RegistroForm(forms.ModelForm):
	password = forms.CharField(label='Password',widget=forms.PasswordInput)

	class Meta:
		model = Usuario
		fields = ['nombre','apellido','username','password']

	def save(self,commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password'])
		if commit:
			user.save()
		return user

class CuentaForm(forms.ModelForm):
	class Meta:
		model = Cuenta
		fields = ['nombre_cuenta','balance']	

class TransaccionForm(forms.ModelForm):
	"""Instancia de un formulario para registrar las transacciones"""
	class Meta:	
		model = Registros
		fields = [
				'id_cuenta',
				'id_movimiento',
				'id_actividad',
				'id_subactividad',
				'importe',
				'id_formapago',
				'fecha',
				'hora',
				'beneficiario',
				'nota',
				]

		labels = {
			'id_actividad':'Actividad',
			'id_subactividad':'Subactividad',
			'id_movimiento':'Tipo de movimiento',
			'id_formapago':'Forma de pago',
			'id_cuenta':'Cuenta',
		}
		widget = {
			# 'fecha': forms.DateField(required=True,widget=forms.DateInput(format='%Y-%m-%d',
			# 			attrs={'type':'date'}),
			# 			input_formats=['%Y-%m-%d'])
			'fecha': forms.DateInput(format='%Y-%m-%d',attrs={'type':'date'})
		}

GEFs/views.py
from django.shortcuts import render,redirect
from .models import Cuenta, Registros, Usuario, Formapago
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, RegistroForm, CuentaForm, TransaccionForm

# Create your views here.

# def filtro_cuenta(request):
# 	'''Filtra los registros en base a una cuenta seleccionada'''
# 	cuenta = request.POST
# 	cuenta_seleccionada = cuenta['cuenta']
	


def cuenta_registro(request,id_cuenta):
	'''Renderiza los registros realizados por cada cuenta'''
	registros = Registros.objects.select_related('id_actividad','id_subactividad'
		).filter(id_cuenta=id_cuenta)
	return render(request,'GEFs/registros.html',{'registros':registros})

def eliminar_registro(request,id_registro):
	Registros.objects.get(pk=id_registro).delete()
	return redirect('GEFs:registros')

def eliminar_cuenta(request,id_cuenta):
	Cuenta.objects.get(pk=id_cuenta).delete()
	return redirect('GEFs:cuentas')

@login_required
def modificar_cuenta(request,id_cuenta):
	'''Actualizar el nombre y/o el balance de cada cuenta'''
	cuenta = Cuenta.objects.get(id_cuenta=id_cuenta)
	if request.method != 'POST':
		form = CuentaForm()
	else:
		form = CuentaForm(request.POST)
		if form.is_valid:
			cuenta_modificada = form.save(commit=False)
			cuenta_modificada.id_cuenta = id_cuenta
			cuenta_modificada.id_usuario = request.user 
			cuenta_modificada.save()
			return redirect('GEFs:cuentas')

	context = {
		'form':form,
		'cuenta':cuenta,
	}
	return render(request,'GEFs/mcuenta.html',context)

def nuevo_registro(request):
	'''Inserta registros en una cuenta particular a travez de formulario 
		TransaccionForm'''
	usuario = request.user	
	if request.method != 'POST':
		form = TransaccionForm()
		form.fields['id_cuenta'].choices = [(value.id_cuenta,value.nombre_cuenta) for value in usuario.cuenta_set.all()]
	else:
		form = TransaccionForm(request.POST)
		if form.is_valid:
			transaccion = form.save(commit=False)
			transaccion.id_usuario = usuario
			#Modificamos el balance de la cuenta en base al monto de la transaccion
			if transaccion.id_movimiento.tipo_movimiento in ['Gasto','Transferencia']:
				#Almacenamos la cuenta desde su atributo id_cuenta
				cuenta = transaccion.id_cuenta
				#Si es gasto o transferencia disminuimos el saldo
				cuenta.balance -= transaccion.importe
				cuenta.save()
			else:
				cuenta = transaccion.id_cuenta
				cuenta.balance += transaccion.importe
				cuenta.save()
			transaccion.save()
			return redirect('GEFs:registros')

	return render(request,'GEFs/nuevo_registro.html',{'form':form})			

@login_required
def nueva_cuenta(request,id_usuario):
	'''Ingresa una nueva cuenta para un usuario en particular'''
	usuario = Usuario.objects.get(id_usuario=id_usuario)

	if request.method != 'POST':
		form = CuentaForm()
	else:
		form = CuentaForm(request.POST)
		if form.is_valid:
			cuenta = form.save(commit=False)
			cuenta.id_usuario = usuario
			cuenta.save()
			return redirect('GEFs:cuentas')

	context = {
		'form':form,
		'usuario':usuario,
	}
	return render(request,'GEFs/nueva_cuenta.html',context)

def primera_cuenta(user):
	'''Se crea una cuenta por default "efectivo" para un nuevo usuario'''
	Cuenta.objects.create(nombre_cuenta='Efectivo',balance='0',id_usuario=user)

def user_register(request):
	if request.method == 'POST':
		form = RegistroForm(request.POST)
		if form.is_valid:
			user = form.save()
			login(request,user)
			primera_cuenta(user)
			return redirect('GEFs:cuentas')
	else:		
		form = RegistroForm()

	return render(request,'GEFs/user_register.html',{'form':form})

def mi_login(request):
	if request.method =='POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			user = form.get_user()
			if user:
				login(request,user)
				return redirect('GEFs:cuentas')
	else:
		form = LoginForm()
	return render(request,'GEFs/login.html',{'form':form})

def mi_logout(request):
	logout(request)
	return redirect('GEFs:login')

@login_required
def cuentas(request):
	'''Muestra las cuentas que han sido creadas.'''
	cuentas = Cuenta.objects.filter(id_usuario=request.user)
	context = {
		'cuentas':cuentas
	}
	return render(request,'GEFs/cuentas.html',context)

@login_required
def registros(request):
	'''Muestra los registros que han sido creados.'''
	usuario = request.user.id_usuario
	cuentas = Cuenta.objects.filter(id_usuario=usuario)
	registros = Registros.objects.select_related('id_actividad',
			'id_subactividad').filter(id_usuario=usuario)
	context = {
		'registros': registros,
		'cuentas': cuentas,
	}
	return render(request,'GEFs/registros.html',context)

GEFs/templates/GEFs/base.html
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#"> Track your money</a>

    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNav">  
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'GEFs:cuentas'  %}">Cuentas<span class="sr-only"></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'GEFs:registros' %}">Registros</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'GEFs:nuevo_registro' %}">+ Registros</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'GEFs:logout' %}">Salir</a>
            </li>
        </ul>
        <span class="navbar-text text-end">Hola, {{user.nombre}}</span>    
    </div>
    {%endif %} 
</nav>
{% block content%}{%endblock content%}

GEFs/templates/GEFs/cuentas.html
{% extends 'GEFs/base.html'%}

{% block content%}
	{% for cuenta in cuentas%}
	<div class="card mb-3">
        <h4 class="card-header">
        	<a href="{%url 'GEFs:cuenta_registro' cuenta.id_cuenta%}">{{cuenta}}</a> 
        	<small><a href="{%url 'GEFs:modificar_cuenta' cuenta.id_cuenta %}">Editar</a></small>
			<small><a href="{%url 'GEFs:eliminar_cuenta' cuenta.id_cuenta %}">Eliminar</a></small></small>
        </h4>
        <div class="card-body"> S/. {{cuenta.balance}}</b></div>
    </div>
	{% if forloop.last %}
	<li class="list-group-item">
		<a href="{%url 'GEFs:nueva_cuenta' cuenta.id_usuario.id_usuario %}">Nueva cuenta</a>
	</li>
	{%endif%}
	{%empty%}
	<li class="list-group-item">Ninguna cuenta fue agregada.</li>
	{% endfor%}
</ul>
{%endblock content%}

GEFs/templates/GEFs/login.html
{% extends 'GEFs/base.html'%}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{%block content%}
	<div class="d-flex justify-content-center">
    <div class="w-50">
			<h1>Login</h1>
			<form method="POST">
				{% csrf_token%}
				{% bootstrap_form form %}	
				<button type="submit" class="btn btn-primary">Entrar</button>
				<a class="btn btn-secondary" href="{% url 'GEFs:user_register'%}" role="button">Nuevo Usuario</a>	
			</form>
		</div>
	</div>
{%endblock content%}

GEFs/templates/GEFs/mcuenta.html
{% extends 'GEFs/base.html'%}
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% block content %}
	<div class="d-flex justify-content-center">
    <div class="w-50">
			<h1>Modificar cuenta</h1>
			<form action="{% url 'GEFs:modificar_cuenta' cuenta.id_cuenta %}" method="POST">
				{% csrf_token%}
				{% bootstrap_form form %}
				<button type="submit" class="btn btn-primary">Modificar</button>
			</form>
		</div>
	</div>
	{% endblock %}

GEFs/templates/GEFs/nueva_cuenta.html
{% extends 'GEFs/base.html'%}
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% block content%}
	<div class="d-flex justify-content-center">
        <div class="w-50">
			<h1>Nueva cuenta</h1>
			<form action="{% url 'GEFs:nueva_cuenta' usuario.id_usuario %}" method="POST">
			{%csrf_token%}
			{% bootstrap_form form %}
			<button type="submit" class="btn btn-primary">Crear</button>
			</form>
		</div>
	</div>
  {% endblock content%}

GEFs/templates/GEFs/nuevo_registro.html
{% extends 'GEFs/base.html'%}
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
	{% block content%}
	<div class="d-flex justify-content-center">
    <div class="w-50">
			<h1>Nuevo registro</h1>
			<form action="{% url 'GEFs:nuevo_registro' %}" method="POST">
				{% csrf_token%}
				{% bootstrap_form form %}
				<button type="submit" class="btn btn-primary">Crear</button>
			</form>
		</div>
	</div>
	{% endblock %}

GEFs/templates/GEFs/registro_cuenta.html
{%extends 'GEF/base.html'%}

{%block content%}
  {%for registro in registros%}
      <div class="card mb-3">
        <h4 class="card-header">{{registro.fecha|date:'M d, Y'}}
          <small>
              {{registro.hora|time:"H:i:s"}}
              <a href="{%url 'GEFs:eliminar_registro' registro.id_registro%}">Eliminar</a>
          </small>
        </h4>
        {%if registro.id_movimiento.id_movimiento == 1 %}
            <div class="card-body">{{registro.id_actividad.tipo_actividad}}, {{registro.id_subactividad.tipo_subactividad}} <b>-{{registro.importe}}</b></div>
        {%else%}
            <div class="card-body">{{registro.id_actividad.tipo_actividad}}, {{registro.id_subactividad.tipo_subactividad}} <b>+{{registro.importe}}</b></div>
        {%endif%}
      </div>
    {%empty%}
      <li class="list-group-item">Ningun registro realizado</li>
    
  {%endfor%}
{%endblock content%}

GEFs/templates/GEFs/registros.html
{%extends 'GEFs/base.html'%}

{%block content%}
  {%for registro in registros%}
      <div class="card mb-3">
        <h4 class="card-header">{{registro.fecha|date:'M d, Y'}}
          <small>
              {{registro.hora|time:"H:i:s"}}
              <a href="{%url 'GEFs:eliminar_registro' registro.id_registro%}">Eliminar</a>
          </small>
        </h4>
        {%if registro.id_movimiento.id_movimiento == 1 %}
            <div class="card-body">{{registro.id_actividad.tipo_actividad}}, {{registro.id_subactividad.tipo_subactividad}} <b>-{{registro.importe}}</b></div>
        {%else%}
            <div class="card-body">{{registro.id_actividad.tipo_actividad}}, {{registro.id_subactividad.tipo_subactividad}} <b>+{{registro.importe}}</b></div>
        {%endif%}
      </div>
    {%empty%}
      <li class="list-group-item">Ningun registro realizado</li>
  {%endfor%}
{%endblock content%}

GEFs/templates/GEFs/user_register.html
{% extends 'GEFs/base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
	<div class="d-flex justify-content-center">
        <div class="w-50">
			<h1>Registro de Usuarios</h1>
			<form method="POST">
				{%csrf_token%}
				{% bootstrap_form form %}
				<button type="submit"  class="btn btn-primary">Registrar</button>
			</form>
		</div>	
	</div>	
{% endblock %}